### ISSUE TITLE
readme/howto?

### ISSUE THREAD

**Issue by Hans-Maulwurf** [kotfic/reddit_elfeed_wrapper#1]
hey, could u give a short introduction on how to use this?

**Comment by kotfic** [comment]
@Hans-Maulwurf  honestly i've abandoned this project and I don't really use elfeed anymore. The idea was to write a little flask server to run locally that converts reads in rss feeds from reddit and does whatever cleanup/conversion is necessary to get them to look good with elfeed. This was just an afternoon hack and it isn't really used, or meant to be used.
